# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(271, 309)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Medium")
        Form.setFont(font)
        icon = QtGui.QIcon.fromTheme("D:\\PM\\AAMM\\Acceptimage.ico")
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QWidget{\n"
"    background:#454545\n"
"}\n"
"QPushButton {\n"
"    background:#e3e1e1;\n"
"    font-size:16px\n"
"}\n"
"QLineEdit{\n"
"    color:#e3e1e1;\n"
"    text-align:right\n"
"}\n"
"QLabel{\n"
"    color:#e3e1e1;\n"
"    text-align:right;\n"
"    font-size:15px\n"
"}\n"
"")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(70, 170, 131, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 230, 131, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(40, 90, 181, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 60, 141, 21))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Accepter"))
        self.pushButton.setText(_translate("Form", "start"))
        self.pushButton_2.setText(_translate("Form", "stop"))
        self.label.setText(_translate("Form", "Word accept (eng)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
